version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'dev@dev.dev'
      PGADMIN_DEFAULT_PASSWORD: 'dev'
    ports:
      - '4000:80'
    depends_on:
      - postgres
